Tdl 18579 add unit test cases
singer-io/tap-zendesk-chat pull request #44
Opened 2022-07-15 07:30 UTC by kethan1122

# Description of change

- add unittest cases for http error handling, context fns, metadata fns etc..
- fixed expected record count in test_bookmarks.py for integration tests (been failing from long time)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-07-18 06:49 UTC, savan-chovatiya requested changes
Add pytest coverage thing in config.yml so code coverage can be visible in artifacts.
Reference: https://github.com/singer-io/tap-sailthru/blob/main/.circleci/config.yml#L29-L38

2022-07-18 07:29 UTC, kethan1122 commented on tests/unittests/test_auth_discovery.py
> +        except HTTPError as e:
changed

2022-07-18 07:29 UTC, kethan1122 commented
> Add pytest coverage thing in config.yml so code coverage can be visible in artifacts. Reference: https://github.com/singer-io/tap-sailthru/blob/main/.circleci/config.yml#L29-L38

2022-07-18 09:03 UTC, savan-chovatiya commented on tests/unittests/test_auth_discovery.py
> +        except HTTPError as e:
Please update all the try-except in unit tests.

2022-09-07 05:47 UTC, savan-chovatiya approved these changes

2022-09-07 05:56 UTC, merged